module.exports = {
  plugins: ['@trivago/prettier-plugin-sort-imports'],
  tabWidth: 2,
  printWidth: 120,
  semi: true,
  singleQuote: true,
  endOfLine: 'lf',
  arrowParens: 'always',
  trailingComma: 'es5',
  jsxSingleQuote: true,
  importOrder: [
    '^react',
    '<THIRD_PARTY_MODULES>',
    '^@/(.*)$',
    '^(app|src)/(.*)$',
    '^(components|src/components)/(.*)$',
    '^(screens|src/screens)/(.*)$',
    '^(hooks|src/hooks)/(.*)$',
    '^(utils|src/utils)/(.*)$',
    '^(constants|src/constants)/(.*)$',
    '^(types|src/types)/(.*)$',
    '^(services|src/services)/(.*)$',
    '^(store|src/store)/(.*)$',
    '^(assets|src/assets)/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
